eslint-community/eslint-plugin-eslint-plugin

- README.md
- docs/rules/no-identical-tests.md
- lib/rules/no-identical-tests.js
- tests/lib/rules/no-deprecated-report-api.js
- tests/lib/rules/no-identical-tests.js
- tests/lib/rules/report-message-format.js
- tests/lib/rules/require-meta-fixable.js
> New: disallow identical tests

- README.md
- docs/rules/no-identical-tests.md
- lib/rules/no-identical-tests.js
- tests/lib/rules/no-identical-tests.js
<del>this is WIP, as the trailing commas have not been handled.</del>
it simply remove the identical tests, so may cause incorrect indent. any suggestions? @not-an-aardvark
> add --fix to no-identical-tests.

- README.md
- docs/rules/prefer-output-null.md
- lib/rules/prefer-output-null.js
- tests/lib/rules/no-deprecated-report-api.js
- tests/lib/rules/prefer-output-null.js
> New: rule prefer-output-null

- README.md
- docs/rules/fixer-return.md
- lib/rules/fixer-return.js
- tests/lib/rules/fixer-return.js
> New: fixer-return

- lib/rules/no-identical-tests.js
- tests/lib/rules/no-identical-tests.js
> Update: no-identical-tests despite of properties order.

- README.md
- lib/rules/fixer-return.js
- lib/rules/no-identical-tests.js
added these rules:
- no-identical-tests
- <del>prefer-output-null</del>
- fixer-return
these are not added:
- consistent-output
- prefer-placeholders
- report-message-format
> Breaking: add some rules to recommended config

- README.md
- docs/rules/test-case-property-ordering.md
- lib/rules/test-case-property-ordering.js
- tests/lib/rules/test-case-property-ordering.js
enable it on eslint codebase: https://github.com/eslint/eslint/pull/9040
my concern is we didn't enable `object-curly-newline`, this may fixing some code like this:
```js
{ code: "var [ x, y ] = z",
options: ["always"],
parserOptions: { ecmaVersion: 6 } },
```
looks so, hmm... strange!
> Update: add autofixing to test-case-property-ordering. (fixes #31)

- lib/rules/no-identical-tests.js
- lib/rules/test-case-property-ordering.js
- lib/rules/test-case-shorthand-strings.js
rules: no-identical-tests, test-case-property-ordering, test-case-shorthand-string.
> Fix: some rules crash if tests array has missing elements (fixes #35).

- README.md
We should really autogenerate that table :confused:
> Docs: add missing fixable icon to `no-deprecated-context-methods`

- .eslintrc.yml
- README.md
- docs/rules/require-meta-docs-url.md
- lib/rules/require-meta-docs-url.js
- tests/lib/rules/require-meta-docs-url.js
(Fixes #55)
This is a reference implementation of #55.
1. This rule validates `meta.docs.url` property. 
2. This rule makes `meta.docs.url` property automatically if people set `pattern` option. This would reduce the cost of plugin's contributors.
> New: require-meta-docs-url (fixes #55)

- lib/rules/report-message-format.js
- tests/lib/rules/report-message-format.js
This fixes a bug where `report-message-format` wouldn't check message specified in `meta.messages`, so if a rule was using `messageId`s it could inadvertently use messages that don't match the required format.
I originally noticed this bug in https://github.com/eslint/eslint/pull/11033#discussion_r239992302.
> Update: ensure report-message-format checks formatting in meta.messages

- .eslintrc.yml
- README.md
- docs/rules/meta-property-ordering.md
- lib/rules/meta-property-ordering.js
- tests/lib/rules/meta-property-ordering.js
> New: meta-property-ordering (fixes #62)

- lib/rules/require-meta-type.js
- lib/utils.js
- tests/lib/rules/require-meta-type.js
> Fix: Check for meta type even when using a function reference (fixes #83)

- README.md
- docs/rules/require-meta-schema.md
- lib/rules/fixer-return.js
- lib/rules/require-meta-docs-url.js
- lib/rules/require-meta-schema.js
- lib/utils.js
- tests/lib/rules/require-meta-schema.js
The eslint core plugin also has its own rule for the same purpose: https://github.com/eslint/eslint/blob/master/tools/internal-rules/no-invalid-meta.js#L91
> Add new rule `require-meta-schema`

- docs/rules/consistent-output.md
- lib/rules/consistent-output.js
- tests/lib/rules/consistent-output.js
I'd like to ensure that invalid test cases always assert what the output should be.
The existing behavior of the rule is not very useful to me, since contributors of new rules often forget about or are unaware of the "output" assertion, and thus leave it out entirely, which the rule does not warn about.
> Add `always` option to `consistent-output` rule

- lib/rules/require-meta-schema.js
- tests/lib/rules/require-meta-schema.js
Turns out that eslint supports both array and object schemas. eslint itself has a handful of rules that use objects schemas, although array schemas are much more common.
https://eslint.org/docs/developer-guide/working-with-rules#options-schemas
Example rule with object schema: https://github.com/eslint/eslint/blob/master/lib/rules/eqeqeq.js#L29
Example rule with array schema: https://github.com/eslint/eslint/blob/master/lib/rules/func-style.js#L22
> Update `require-meta-schema` rule to allow object schemas (in addition to array schemas)

- lib/utils.js
- tests/lib/rules/require-meta-fixable.js
- tests/lib/utils.js
> Fix: handle spreads in rule meta objects

- README.md
- docs/rules/prefer-object-rule.md
- lib/rules/prefer-object-rule.js
- tests/lib/rules/prefer-object-rule.js
Adds a simple rule to help enforce that a rule uses object style rule definitions instead of function style.
I wanted this to help me migrate a legacy codebase of ~300 rules.
This rule pairs well and help with the `require-meta-*` rules as it allows their fixers to work.
Currently those rules will report an error, but not fix function style rules.
> Add rule `prefer-object-rule`

- lib/rules/test-case-property-ordering.js
- tests/lib/rules/require-meta-docs-url.js
- tests/lib/rules/test-case-property-ordering.js
defaults to ['filename','code','output','options','parser',
'parserOptions','globals','env','errors']
> Breaking: change test-case-property-ordering default options (fixes #79)

- lib/utils.js
- tests/lib/utils.js
Turns out if `create` is a reference, the global scope don't have the reference not only in `nodejsScope`, also broken if `sourceType` is set to `'module'`.
To find the correct reference, I'm searching all `childScopes`, I hope it's fine to do this.
Fixes #106
> Fix: Rule can't find reference of `create` function

- lib/rules/require-meta-schema.js
- package.json
- tests/lib/rules/require-meta-schema.js
> `require-meta-schema`: Fix false positive

- lib/rules/meta-property-ordering.js
- lib/rules/prefer-object-rule.js
- lib/rules/report-message-format.js
- lib/rules/require-meta-docs-description.js
- lib/rules/require-meta-docs-url.js
- lib/rules/require-meta-fixable.js
- lib/rules/require-meta-schema.js
- lib/rules/require-meta-type.js
- lib/utils.js
- tests/lib/utils.js
Make it accept object contains `ast` and optional `scopeManager`, so we can simply just pass `sourceCode` to it. I believe this will fix some reference searching.
> Refactor: `utils.getRuleInfo`

- lib/rules/require-meta-docs-description.js
- tests/lib/rules/require-meta-docs-description.js
Two changes:
* Drastically improves detection of the `description` string value when it can be determined statically, including handling when the description is stored in a constant or created through string concatenation
* If we cannot determine the string value of the `description` statically, then bail out and report no violations, so that users can dynamically generate the description if they'd like to
Fixes #97.
> Improve detection of static `description` strings and ignore non-static descriptions in `require-meta-docs-description` rule

- README.md
it's no longer true for the latest eslint, and global-installed usage is not recommended.
> Docs: rm global-installed usage

- README.md
- docs/rules/require-meta-has-suggestions.md
- lib/rules/require-meta-has-suggestions.js
- tests/lib/rules/require-meta-has-suggestions.js
Suggestable ESLint rules should have a `meta.hasSuggestions` property to indicate that they provide [suggestions](https://eslint.org/docs/developer-guide/working-with-rules#providing-suggestions). This new rule enforces that the `meta.hasSuggestions` property is correctly enabled when a rule provides suggestions, and not enabled when a rule does not provide suggestions.
The change to require suggestable rules to have `meta.hasSuggestions` has been accepted and mentioned in the blog post for the upcoming ESLint 8 breaking changes. So we should adopt this change now to help plugin authors ensure they are compatible with ESLint 8 as soon as possible. The old property `meta.docs.suggestion` was unused anyway.
https://eslint.org/blog/2021/06/whats-coming-in-eslint-8.0.0#rules-with-suggestions-n …
> New: Add new rule `require-meta-has-suggestions`

- docs/rules/require-meta-type.md
The list and explanations come from: https://eslint.org/docs/developer-guide/working-with-rules#rule-basics
> Mention allowed `type` values in `require-meta-type` rule doc

- lib/rules/no-deprecated-report-api.js
- lib/rules/no-missing-placeholders.js
- lib/rules/no-unused-placeholders.js
- lib/rules/prefer-placeholders.js
- lib/rules/prefer-replace-text.js
- lib/rules/report-message-format.js
- lib/utils.js
- tests/lib/rules/no-deprecated-report-api.js
- tests/lib/rules/no-missing-placeholders.js
- tests/lib/rules/no-unused-placeholders.js
- tests/lib/rules/prefer-placeholders.js
- tests/lib/rules/report-message-format.js
- tests/lib/utils.js
Several of our rules check the arguments of `context.report()`. This PR makes some improvements:
1. When inferring the arguments passed to `context.report()` in `utils.getReportInfo()`, take into account the static value of the second argument when available.
2. Update the rules using `utils.getReportInfo()` to also consider the static value or variable declaration of the message argument when necessary.
I noticed these issues because in a number of my plugins, we have stored rule error messages in variables like `const MESSAGE = 'do A instead of B';`, and this prevented many of the eslint-plugin-eslint-plugin rules from operating correctly.
Example of how this improvement enables the `no-deprecated-report-api` rule to correctly autofix this code (previously no autofix):
```js
const …
```
> Improve detection of static arguments of `context.report()` in several rules

- .markdownlint.json
- .markdownlintignore
- README.md
- docs/rules/no-deprecated-report-api.md
- docs/rules/no-missing-placeholders.md
- docs/rules/require-meta-docs-description.md
- docs/rules/require-meta-docs-url.md
- docs/rules/test-case-shorthand-strings.md
- package.json
Add popular tool for enforcing best markdown practices: https://github.com/igorshubovych/markdownlint-cli
Autofixed most violations.
> Add `markdownlint` for doc formatting

- .eslintrc.js
- lib/rules/consistent-output.js
- lib/rules/meta-property-ordering.js
- lib/rules/no-deprecated-context-methods.js
- lib/rules/no-identical-tests.js
- lib/rules/no-missing-placeholders.js
- lib/rules/no-unused-placeholders.js
- lib/rules/no-useless-token-range.js
- lib/rules/prefer-output-null.js
- lib/rules/prefer-placeholders.js
- lib/rules/require-meta-docs-url.js
- lib/rules/require-meta-fixable.js
- lib/rules/test-case-property-ordering.js
- lib/utils.js
- package.json
- tests/lib/index.js
- tests/lib/utils.js
All sorts of cool rules for enforcing/converting to better, modern JavaScript code.
Most of this was autofixed. I disabled a few noisy/undesirable rules.
https://github.com/sindresorhus/eslint-plugin-unicorn
> Add eslint-plugin-unicorn

- .eslintrc.js
- docs/rules/consistent-output.md
- docs/rules/fixer-return.md
- docs/rules/meta-property-ordering.md
- docs/rules/no-deprecated-context-methods.md
- docs/rules/no-deprecated-report-api.md
- docs/rules/no-identical-tests.md
- docs/rules/no-missing-placeholders.md
- docs/rules/no-unused-placeholders.md
- docs/rules/no-useless-token-range.md
- docs/rules/prefer-object-rule.md
- docs/rules/prefer-output-null.md
- docs/rules/prefer-placeholders.md
- docs/rules/prefer-replace-text.md
- docs/rules/report-message-format.md
- docs/rules/require-meta-docs-description.md
- docs/rules/require-meta-docs-url.md
- docs/rules/require-meta-fixable.md
- docs/rules/require-meta-has-suggestions.md
- docs/rules/require-meta-schema.md
- docs/rules/require-meta-type.md
- docs/rules/test-case-property-ordering.md
- docs/rules/test-case-shorthand-strings.md
- package.json
This applies our JavaScript linting to the JavaScript code samples in the markdown documentation files. Goal is to generally improve the quality, reliability, and consistency of our documentation.
* Autofixes styling/formatting/whitespace
* Fixes and prevents syntax errors
> Add eslint-plugin-markdown for JavaScript code samples in documentation

- docs/rules/fixer-return.md
- docs/rules/meta-property-ordering.md
- docs/rules/no-deprecated-context-methods.md
- docs/rules/no-deprecated-report-api.md
- docs/rules/no-identical-tests.md
- docs/rules/no-missing-placeholders.md
- docs/rules/no-unused-placeholders.md
- docs/rules/no-useless-token-range.md
- docs/rules/prefer-object-rule.md
- docs/rules/prefer-output-null.md
- docs/rules/report-message-format.md
- docs/rules/require-meta-docs-url.md
- docs/rules/require-meta-fixable.md
- docs/rules/require-meta-has-suggestions.md
- docs/rules/require-meta-schema.md
- docs/rules/test-case-property-ordering.md
- docs/rules/test-case-shorthand-strings.md
- tests/lib/rule-setup.js
Adds tests to ensure that our rule docs have notices to indicate whether they are fixable and/or in the recommended config. These notices match the format used by ESLint itself. Example: https://eslint.org/docs/rules/no-extra-semi
Also adds tests for various other aspects of rule docs and that each rule has a documentation file and test file.
> Add rule documentation consistency tests

- docs/rules/require-meta-schema.md
- lib/rules/require-meta-schema.js
- tests/lib/rules/require-meta-schema.js
Flags a violation if an empty schema is specified but rule options are used.
This new check is similar to how:
* `require-meta-fixable` checks that `fixable: true` is specified when an autofixer is found 
* `require-meta-has-suggestions` checks that `hasSuggestions: true` is specified when suggestions are provided
Note: this is *not* a breaking change, since ESLint itself already prevents rules from using options when an empty rule schema is specified, so it's not possible that this new violation could be flagged on existing rules.
> Flag a violation when rule options are used but an empty schema is specified in `require-meta-schema` rule

- .eslintrc.js
- lib/rules/consistent-output.js
- lib/rules/fixer-return.js
- lib/rules/meta-property-ordering.js
- lib/rules/no-deprecated-context-methods.js
- lib/rules/no-deprecated-report-api.js
- lib/rules/no-identical-tests.js
- lib/rules/no-missing-placeholders.js
- lib/rules/no-unused-placeholders.js
- lib/rules/no-useless-token-range.js
- lib/rules/prefer-object-rule.js
- lib/rules/prefer-output-null.js
- lib/rules/prefer-placeholders.js
- lib/rules/prefer-replace-text.js
- lib/rules/report-message-format.js
- lib/rules/require-meta-docs-description.js
- lib/rules/require-meta-docs-url.js
- lib/rules/require-meta-fixable.js
- lib/rules/require-meta-has-suggestions.js
- lib/rules/require-meta-schema.js
- lib/rules/require-meta-type.js
- lib/rules/test-case-property-ordering.js
- lib/rules/test-case-shorthand-strings.js
This was autofixed.
We should use our own rules internally as an additional means of testing/dogfooding them in real-world usage.
> Enable `meta-property-ordering` rule internally

- .gitignore
- package.json
The current test coverage data looks like the below table, and I set the minimum code coverage percentages based on this.
As a follow-up, we can add tests to cover the uncovered lines, and possibly raise the test coverage percentages further.
This addition should help prevent developers from submitting PRs which are missing test coverage, saving everyone time during PR review.
https://github.com/istanbuljs/nyc
```
-----------------------------------|---------|----------|---------|---------|-------------------
File                               | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s 
-----------------------------------|---------|----------|---------|---------|-------------------
All files                          |   98.36 |    96.43 |   98.94 |   98.65 | …
```
> Enforce minimum test code coverage

- README.md
- docs/rules/fixer-return.md
- lib/rules/fixer-return.js
- tests/lib/rules/fixer-return.js
Report a violation on fix functions that never return a fix.
1. Catch fix functions that have a return statement but never actually return a fix (i.e. fix functions that only ever return undefined or similar values that are obviously not fixes).
2. Allow fix functions to have some code paths that do not return a fix (it's allowed for a fix function to bail out / return early and avoid fixing in some unsafe situations).
I would consider these both bug fixes to reduce false positives and false negatives.
This PR also increases the test code coverage for this rule up to 100%.
```
create (context) {
fix (fixer) {
if (foo) {
return; // no autofix in this case
}
return fixer.foo();
},
});
},
};
```
```
create (context) { …
```
> Improve detection of fix functions that never return a fix in `fixer-return` rule

- lib/rules/fixer-return.js
- tests/lib/rules/fixer-return.js
Also improves test coverage including updating the tests to ensure each violation is reported at the correct location (since the location differs depending on the function type).
The lack of coverage for arrow functions was a bug / omission in the rule.
> Update `fixer-return` rule to handle arrow function expressions

- README.md
- docs/rules/no-only-tests.md
- lib/rules/no-only-tests.js
- tests/lib/rules/no-only-tests.js
Fixes #118.
I named it `no-only-tests` for consistency with the [no-identical-tests](https://github.com/not-an-aardvark/eslint-plugin-eslint-plugin/blob/master/docs/rules/no-identical-tests.md) rule name. I would be equally happy to name it `no-test-only` or something else. Let me know if you want me to change the name.
We should enable this as a `recommended` rule in v4 (#120).
Most other test frameworks have a similar rule to this:
* [ava/no-only-test](https://github.com/avajs/eslint-plugin-ava/blob/main/docs/rules/no-only-test.md)
* [jest/no-focused-tests](https://github.com/jest-community/eslint-plugin-jest/blob/main/docs/rules/no-focused-tests.md)
* [mocha/no-exclusive-tests](https://github.com/lo1tuma/eslint-plugin-mocha/blob/master/docs/rules/no-exclusive-tests.md)
* …
> Add new rule `no-only-tests`

- lib/index.js
This will make no needs to add `eslint-plugin` to `plugins` manually if a preset is enabled.
> add the plugin name to plugins prop of presets

- docs/rules/meta-property-ordering.md
- docs/rules/no-deprecated-context-methods.md
- docs/rules/no-deprecated-report-api.md
- docs/rules/prefer-output-null.md
- docs/rules/prefer-placeholders.md
- docs/rules/prefer-replace-text.md
- docs/rules/report-message-format.md
- docs/rules/require-meta-docs-description.md
- docs/rules/require-meta-docs-url.md
- docs/rules/require-meta-fixable.md
- docs/rules/require-meta-has-suggestions.md
- docs/rules/require-meta-schema.md
- docs/rules/require-meta-type.md
- docs/rules/test-case-property-ordering.md
- tests/lib/rule-setup.js
* Start rule doc titles with a capital letter
* Test to ensure rule doc titles include the description from rule.meta.docs.description
> Ensure rule doc titles match rule descriptions

- package.json
This ignore pattern is no longer necessary (ESLint lints .eslintrc.js as of [ESLint 7](https://eslint.org/blog/2020/05/eslint-v7.0.0-released)), and it was causing ESLint to lint some files in node_modules for me locally.
> Remove unnecessary ignore pattern from internal js linting

- lib/rules/require-meta-type.js
- tests/lib/rules/require-meta-type.js
* Fixes false negatives
* Improves the reporting location
> Fix: Fix false negatives and reporting location in `require-meta-type` rule

- lib/rules/require-meta-docs-description.js
> Chore: Fully adopt `messageId` in `require-meta-docs-description` rule

- docs/rules/require-meta-fixable.md
- lib/rules/require-meta-fixable.js
- tests/lib/rules/require-meta-fixable.js
False positives fixed:
* When `meta.fixable` uses a variable
False negatives fixed:
* When there's a fixer but `meta.fixable` = null
* When there's a fixer but `meta.fixable` = undefined
Also improves reporting location.
I'll be opening a few more PRs after this to make similar fixes to other rules.
> Fix: Fix false positives/negatives in `require-meta-fixable` rule

- lib/rules/require-meta-docs-url.js
- tests/lib/rules/require-meta-docs-url.js
* Add static value detection for `url` variables
* Ignore when we can't statically determine the value of a given `url`, so people can use their own `getUrl()` function if they want
* Improve reporting location and tests for this
* Use `messageId`
* Add tests
> Fix: Improve detection of static `url` strings in `require-meta-docs-url` rule

- lib/rules/require-meta-schema.js
- tests/lib/rules/require-meta-docs-description.js
- tests/lib/rules/require-meta-has-suggestions.js
- tests/lib/rules/require-meta-schema.js
We need to ensure that the rules correctly handle `null` / `undefined` as the value of the meta properties since these values are commonly used as placeholder values.
Fixes one bug and adds test coverage.
> Fix: Ensure `require-meta-*` rules test `null` / `undefined` property values

- README.md
- docs/rules/prefer-message-ids.md
- lib/rules/consistent-output.js
- lib/rules/meta-property-ordering.js
- lib/rules/no-deprecated-context-methods.js
- lib/rules/no-deprecated-report-api.js
- lib/rules/no-missing-placeholders.js
- lib/rules/no-unused-placeholders.js
- lib/rules/no-useless-token-range.js
- lib/rules/prefer-message-ids.js
- lib/rules/prefer-output-null.js
- lib/rules/prefer-placeholders.js
- lib/rules/prefer-replace-text.js
- lib/rules/report-message-format.js
- lib/rules/test-case-property-ordering.js
- lib/rules/test-case-shorthand-strings.js
- tests/lib/rules/consistent-output.js
- tests/lib/rules/meta-property-ordering.js
- tests/lib/rules/no-deprecated-report-api.js
- tests/lib/rules/prefer-message-ids.js
- tests/lib/rules/prefer-output-null.js
- tests/lib/rules/prefer-replace-text.js
- tests/lib/rules/test-case-shorthand-strings.js
* Adds new rule (see rule doc)
* Updates other rules to comply with it
> New: Add new rule `prefer-message-ids`

- lib/rules/require-meta-has-suggestions.js
- tests/lib/rules/require-meta-has-suggestions.js
If the suggestions array is initialized as an empty array variable, we need to assume that someone may have pushed suggestion objects to it, so we should consider that a usage of suggestions.
Previously, this rule incorrectly assumed that using `const suggest = []; ... context.report({suggest,...});` meant the rule was not using suggestions.
Real world example here: https://github.com/eslint/eslint/blob/master/lib/rules/no-nonoctal-decimal-escape.js#L91
> Fix: Fix false positive with empty array variable in `require-meta-has-suggestions` rule

- lib/rules/prefer-message-ids.js
- tests/lib/rules/prefer-message-ids.js
In some rules, `context` is passed to functions that eventually call `context.report()`, like [`no-duplicate-imports`](https://github.com/eslint/eslint/blob/8be8a36010145dfcd31cbdd4f781a91989e3b1bd/lib/rules/no-duplicate-imports.js#L176) or [`padding-lines-between-statements`](https://github.com/eslint/eslint/blob/8be8a36010145dfcd31cbdd4f781a91989e3b1bd/lib/rules/padding-line-between-statements.js#L244), and that will prevent this existing rule from flagging such instances of `context.report({ message: ... });`.
So in addition to flagging that, we should also flag when rules are simply missing `meta.messages`, as all rules using message IDs should have at least one violation message defined in that object.
This will unblock this PR: …
> Fix: False negative in `prefer-message-ids` rule

- lib/rules/require-meta-schema.js
Ironically, this rule had the wrong schema. This rule has no options and should not have an empty schema. The schema used here was supposed to be an example in the rule doc file only.
> Fix: Remove erroneous schema from `require-meta-schema` rule

- docs/rules/require-meta-schema.md
- lib/rules/require-meta-schema.js
- tests/lib/rules/require-meta-schema.js
> New: Add `requireSchemaPropertyWhenOptionless` option to `require-meta-schema` rule

- lib/rules/require-meta-schema.js
- tests/lib/rules/require-meta-schema.js
Fixes #182.
After this is merged, I will follow-up to convert the autofix to a suggestion, as per #183.
> Fix: Only autofix when no options present in `require-meta-schema` rule

- package.json
This is technically a breaking change because we still support Node 13 but eslint-utils v3 does not.
https://github.com/mysticatea/eslint-utils/releases/tag/v3.0.0
Planned for v4 release (https://github.com/not-an-aardvark/eslint-plugin-eslint-plugin/issues/120).
> Chore: Update `eslint-utils` to v3

- lib/index.js
- lib/utils.js
- package.json
The changes in this PR were autofixed. I disabled rules in a few places where it was going to require a more complicated, manual fix (we should fix these sometime).
This is needed for #186.
https://github.com/sindresorhus/eslint-plugin-unicorn/releases/tag/v36.0.0
> Chore: Upgrade `eslint-plugin-unicorn` to v36

- lib/rules/prefer-object-rule.js
- lib/utils.js
- tests/lib/rules/meta-property-ordering.js
- tests/lib/rules/prefer-message-ids.js
- tests/lib/rules/prefer-object-rule.js
- tests/lib/rules/report-message-format.js
- tests/lib/rules/require-meta-docs-description.js
- tests/lib/rules/require-meta-docs-url.js
- tests/lib/rules/require-meta-fixable.js
- tests/lib/rules/require-meta-has-suggestions.js
- tests/lib/rules/require-meta-schema.js
- tests/lib/rules/require-meta-type.js
- tests/lib/utils.js
Fixes #157. I recommend we add this to the upcoming v4 release (#120).
This change updates most rules (rules using our util `getRuleInfo` to read rule `create`/`meta` data) to support rules defined using the ES modules syntax as follows:
```js
export default {
meta: {},
create(context) {}
};
```
TODO:
```
const rule = { meta: {}, create(context) {} }; 
export default rule;
```
> Breaking: Support ESM rules

- docs/rules/meta-property-ordering.md
- lib/rules/meta-property-ordering.js
- lib/rules/no-only-tests.js
- lib/rules/require-meta-schema.js
- tests/lib/rules/meta-property-ordering.js
It makes most sense to order the new ESLint 8 property `meta.hasSuggestions` (whether a rule provides suggestions) after the related property `meta.fixable` (whether a rule is autofixable).
https://eslint.org/blog/2021/06/whats-coming-in-eslint-8.0.0#rules-with-suggestions-now-require-the-metahassuggestions-property
> Breaking: Add `meta.hasSuggestions` property to `meta-property-ordering` rule

- lib/rules/report-message-format.js
- tests/lib/rules/report-message-format.js
Fixes #192.
Part of v4 release (#120).
> Breaking: Update `report-message-format` to also apply to suggestion messages

- lib/rules/fixer-return.js
- lib/rules/prefer-replace-text.js
- lib/utils.js
- tests/lib/rules/fixer-return.js
- tests/lib/rules/prefer-replace-text.js
- tests/lib/utils.js
These rules should apply to both autofix and suggestion fixer functions.
Updating these two rules together since they share the same logic.
Fixes #193
Fixes #190
Part of v4 release (#120).
> Breaking: Update `fixer-return` and `prefer-replace-text` rules to also apply to suggestion fixer functions

- package.json
espree and eslint-scope has been upgrade in https://github.com/not-an-aardvark/eslint-plugin-eslint-plugin/pull/186, to ensure the same version as eslint v8.0.0
fixes #188
> Chore: upgrade dev deps (fixes #188)

- lib/rules/fixer-return.js
- tests/lib/rule-setup.js
All rules should have a category of either `Rules` or `Tests` since this is how those presets are generated.
Technically, this isn't a breaking change, since we're allowed to modify these presets any time, according to the README:
> The list of recommended rules will only change in a major release of this plugin. However, new non-recommended rules might be added in a minor release of this plugin. Therefore, the using the all, rules, and tests presets is not recommended for production use, because the addition of new rules in a minor release could break your build. 
Part of v4 release (#120).
> Breaking: Add `fixer-return` to `rules` preset

- docs/rules/require-meta-docs-url.md
- tests/lib/rule-setup.js
Add test to ensure:
1. Any rule with options has a `## Options` section in its rule doc.
2. Any named rule options (for example, the `pattern` option for the `require-meta-docs-description` rule) are mentioned in the rule doc.
Based on the same test I wrote here: https://github.com/ember-cli/eslint-plugin-ember/blob/4f26c0bc7e34400007e02939a9c6e183078a3e87/tests/rule-setup.js#L111
Eventually, I'd like to add a lint rule to enforce these "rule setup" tests for any eslint plugin.
> Ensure rule docs mention all rule options

- lib/rules/prefer-output-null.js
- package.json
- tests/lib/rules/prefer-message-ids.js
- tests/lib/rules/prefer-output-null.js
- tests/lib/rules/require-meta-schema.js
Before
```
-----------------------------------|---------|----------|---------|---------|-------------------
File                               | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s 
-----------------------------------|---------|----------|---------|---------|-------------------
All files                          |   99.16 |     98.4 |   99.09 |   99.42 |     
```
After
```
-----------------------------------|---------|----------|---------|---------|-------------------
File                               | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s 
-----------------------------------|---------|----------|---------|---------|-------------------
All files                          |   99.58 |    99.26 |   99.09 |   99.85 |   
```
> test: improve test coverage in a few areas

- lib/rules/consistent-output.js
- lib/rules/fixer-return.js
- lib/rules/meta-property-ordering.js
- lib/rules/no-deprecated-context-methods.js
- lib/rules/no-deprecated-report-api.js
- lib/rules/no-identical-tests.js
- lib/rules/no-missing-placeholders.js
- lib/rules/no-only-tests.js
- lib/rules/no-unused-placeholders.js
- lib/rules/no-useless-token-range.js
- lib/rules/prefer-message-ids.js
- lib/rules/prefer-object-rule.js
- lib/rules/prefer-output-null.js
- lib/rules/prefer-placeholders.js
- lib/rules/prefer-replace-text.js
- lib/rules/report-message-format.js
- lib/rules/require-meta-docs-description.js
- lib/rules/require-meta-docs-url.js
- lib/rules/require-meta-fixable.js
- lib/rules/require-meta-has-suggestions.js
- lib/rules/require-meta-schema.js
- lib/rules/require-meta-type.js
- lib/rules/test-case-property-ordering.js
- lib/rules/test-case-shorthand-strings.js
Supported by VSCode/Webstorm/other code editors. Uses TypeScript declaration to give JavaScript hints so code editors can provide information/autocomplete about various rule fields.
https://www.typescriptlang.org/docs/handbook/jsdoc-supported-types.html#type
Idea from: https://github.com/eslint/generator-eslint/pull/113
> Add jsdoc `type` annotation to rules

- tests/lib/rule-setup.js
Ensures each rule has this jsdoc type comment. Otherwise, it would be easily forgotten in new rules.
Follow-up to https://github.com/not-an-aardvark/eslint-plugin-eslint-plugin/pull/228.
> test: add test for rule jsdoc type comment

- lib/utils.js
- tests/lib/rules/require-meta-schema.js
- tests/lib/utils.js
Updates our rules to detect rules that are defined in variables, which is a style I have seen used by some eslint plugins:
```js
const rule = { meta: {}, create(context) {} }; 
export default rule;
```
```js
const rule = { meta: {}, create(context) {} }; 
module.exports = rule;
```
Follow-up to previous work around detecting additional types of rules and variables used inside rules:
* https://github.com/not-an-aardvark/eslint-plugin-eslint-plugin/pull/177
* https://github.com/not-an-aardvark/eslint-plugin-eslint-plugin/pull/225
Note that this could be considered either a fix or a breaking change since it will result in additional rules detected by our rules in some plugins.
> fix: detect rules exported using a variable

- lib/utils.js
- tests/lib/rules/prefer-object-rule.js
- tests/lib/rules/require-meta-docs-url.js
- tests/lib/utils.js
Updates our rules to detect old function-style rules that are defined in variables:
```js
const rule = function(context) { return {} };
export default rule;
```
```js
const rule = function(context) { return {} };
module.exports = rule;
```
In particular, this is needed so that our [eslint-plugin/prefer-object-rule](https://github.com/not-an-aardvark/eslint-plugin-eslint-plugin/blob/master/docs/rules/prefer-object-rule.md) can detect and automatically convert these old function-style rules to the new object-style format.
Follow-up to:
* https://github.com/not-an-aardvark/eslint-plugin-eslint-plugin/pull/233
* https://github.com/not-an-aardvark/eslint-plugin-eslint-plugin/pull/177
* https://github.com/not-an-aardvark/eslint-plugin-eslint-plugin/pull/225
> fix: detect function-style rules exported using a variable

- .github/workflows/main.yml
Quick PR to upgrade `actions/checkout` and `actions/setup-node` to `v3`.
https://github.com/actions/checkout/releases/tag/v3.0.0
https://github.com/actions/setup-node/releases/tag/v3.0.0
> Upgrade actions used in CI

- README.md
* Provides single unified code sample in "Usage" section
* No more need to specify `plugins` since our configs already do that for the user
* Suggests using the `recommended` config in the "Usage" section instead of just manually enabling a recommended rule
* Demonstrates enabling an optional rule
* Explains when `sourceType` should be set to `script` vs. `module`
Fixes #244.
> Improve config example in README

- lib/utils.js
- tests/lib/rules/no-identical-tests.js
- tests/lib/rules/test-case-property-ordering.js
- tests/lib/utils.js
I think this should cover most cases though it'd be easier if we were walking the AST tree like ESLint actually does, since really what we're wanting to do is check the body of all `BlockStatement` expressions but without walking we have to manually account for every possible place that could be held.
Still this already I think is a huge improvement - I've tried it on `eslint-plugin-jest` and it caught a few violations (including a couple I'd not noticed myself!)
Resolves #248
> Fix: Detect nested test cases

- lib/rules/require-meta-docs-description.js
- lib/rules/require-meta-docs-url.js
- lib/rules/require-meta-fixable.js
- lib/rules/require-meta-has-suggestions.js
- lib/rules/require-meta-schema.js
- lib/rules/require-meta-type.js
- lib/utils.js
- tests/lib/rules/require-meta-docs-description.js
- tests/lib/rules/require-meta-docs-url.js
- tests/lib/rules/require-meta-fixable.js
- tests/lib/rules/require-meta-has-suggestions.js
- tests/lib/rules/require-meta-schema.js
- tests/lib/rules/require-meta-type.js
- tests/lib/utils.js
We're now able to take into account meta properties inside spreads in the `require-meta-*` rules.
1. Introduces new util function `evaluateObjectProperties` which gathers all properties from an object including those behind spreads.
2. Uses this new util function when checking for properties inside the meta object in the `require-meta-*` rules.
Fixes #250.
Example: this is now valid for the `require-meta-type` rule:
```
const extra = { type: 'problem' };
meta: { ...extra },
create(context) {}
};
```
TODO:
> fix: handle properties behind spread syntax in `require-meta-*` rules

- README.md
- docs/rules/no-missing-message-ids.md
- docs/rules/no-unused-message-ids.md
- docs/rules/prefer-message-ids.md
- lib/rules/no-missing-message-ids.js
- lib/rules/no-unused-message-ids.js
- lib/utils.js
- tests/lib/rules/no-missing-message-ids.js
- tests/lib/rules/no-unused-message-ids.js
- tests/lib/utils.js
Fixes https://github.com/not-an-aardvark/eslint-plugin-eslint-plugin/issues/57.
Detects:
* Using a `messageId` that does not exist
* Leaving a message in `meta.messages` that is unused
These were implemented as separate rules because:
* Each is quite complicated on its own and it helps to be able to test them in isolation
* In the event of false positives, the user can just disable one of the rules but not the other
Note that I eliminated many possible false positive scenarios by testing these rules on the ESLint codebase.
TODO
```js
function reportEnd(node, messageId) {
node,
messageId
});
}
```
```js
let messageId;
if (foo) {
messageId = 'abc';
} else {
messageId = 'def';
}
node,
messageId
});
```
```js
node,
messageId: …
```
> Add new rules `no-missing-message-ids` and `no-unused-message-ids`

- .github/workflows/main.yml
This is the latest Node version so we can default to this on some of the version-specific jobs.
> chore: run version-specific CI jobs on Node 18

- docs/rules/consistent-output.md
Update the rule doc to reflect today's reality where this rule is less important/relevant.
This is aligned with how we are removing this rule as a `recommended` rule: https://github.com/not-an-aardvark/eslint-plugin-eslint-plugin/pull/258
> docs: modernize rule doc for `consistent-output`

- README.md
- docs/rules/prefer-object-rule.md
- lib/rules/prefer-object-rule.js
* Improve/simplify wording
* Add context including link to approved RFC with latest plans for ESLint v9
* Remove redundant examples from rule doc
> docs: modernize rule doc for `prefer-object-rule`

- docs/rules/require-meta-schema.md
* Add context including link to approved RFC with latest plans for ESLint v9
> docs: modernize rule doc for `require-meta-schema`

- docs/rules/no-identical-tests.md
* Improve explanation
* Improve examples
* Include latest information from approved RFC for ESLint v9
* Remove non-sensical `When Not To Use It` section
> docs: modernize rule doc for `no-identical-tests`

- .npmpackagejsonlintrc.json
- package.json
Some basic checks for mistakes in package.json. I use this in many other repos.
I fixed a violation about our scripts not being sorted alphabetically.
https://www.npmjs.com/package/npm-package-json-lint
> chore: add npm-package-json-lint

- package.json
* Add `"exports": "./lib/index.js"` to package.json to strictly define NodeJS API (ESLint itself made the [same change](https://eslint.org/docs/8.0.0/user-guide/migrating-to-8.0.0#the-lib-entrypoint-has-been-removed))
Part of v5 release (https://github.com/not-an-aardvark/eslint-plugin-eslint-plugin/issues/230).
> breaking: strictly define Node API

- .github/workflows/main.yml
- package.json
ESLint v6 was released in [2019](https://eslint.org/blog/2019/06/eslint-v6.0.0-released/). Supporting the last two versions, ESLint v7 and ESLint v8, should be sufficient. ESLint v9 will also be released later this year.
Part of v5 release (https://github.com/not-an-aardvark/eslint-plugin-eslint-plugin/issues/230).
> breaking: drop ESLint v6 support

- lib/rules/no-missing-message-ids.js
- lib/rules/no-missing-placeholders.js
- lib/rules/no-unused-placeholders.js
- tests/lib/rules/no-missing-placeholders.js
- tests/lib/rules/no-unused-placeholders.js
Fixes the second part of #57.
Correct placeholder with messageId example: 
```js
meta: {
messages: { myMessageId: 'foo {{bar}}' } 
},
create(context) {
node,
messageId: 'myMessageId',
data: { bar: 'baz' }
});
}
};
```
Part of the V5 release (#230).
> Update `no-missing-placeholders` and `no-unused-placeholders` to handle messageIds

- CHANGELOG.md
they were missing as "breaking:" is not a valid tag in conventional commits.
the commit just added them manually.
> docs: add missing items in v5 changelog

- lib/rules/require-meta-schema.js
- tests/lib/rules/require-meta-schema.js
The goal is to ban obviously-invalid types like `Literal` (string/number) for `meta.schema`, while allowing any kind of variables/function calls/dynamic calculation of the schema.
Previously, a simple variable was allowed, but now these are also allowed:
```js
{
schema: baseRule.meta.schema
}
```
```js
{
schema: getSchema()
}
```
Fixes #273.
> Allow additional types of dynamic schemas in `require-meta-schema` rule

- lib/rules/no-missing-placeholders.js
- lib/rules/no-unused-placeholders.js
- tests/lib/rules/no-missing-placeholders.js
- tests/lib/rules/no-unused-placeholders.js
While investigating #276, I noticed that the existing violation messages were particularly confusing. The messages "the placeholder is missing" or "the placeholder does not exist" are very ambiguous about what they mean.
> Clarify violation messages for `no-missing-placeholders` and `no-unused-placeholders`

- lib/rules/no-missing-placeholders.js
- tests/lib/rules/no-missing-placeholders.js
Fixes https://github.com/not-an-aardvark/eslint-plugin-eslint-plugin/issues/276 (half of it).
Previously, the violation might not even be reported inside the specific context.report() call that it was for.
Now, we report on the data object when it exists.
```js
meta: {
messages: {
foo: 'hello world', // violation should not be reported here
}
},
create(context) {
node,
messageId: 'foo', 
data: { // violation should be reported here
bar: 'abc' 
}
});
},
};
```
> Improve violation reporting location in `no-missing-placeholders`

- lib/rules/no-unused-placeholders.js
- tests/lib/rules/no-missing-placeholders.js
- tests/lib/rules/no-unused-placeholders.js
Fixes #276 (half of it).
Situation 1:
```js
create(context) {
node,
message: 'hello world', // violation should not be reported here
data: {
bar: 'abc' // violation should be reported here on the unused placeholder property
}
});
},
};
```
Situation 2 (even worse because the violation is not even reported inside the specific context.report() call):
```js
meta: {
messages: {
foo: 'hello world', // violation should not be reported here
}
},
create(context) {
node,
messageId: 'foo',
data: {
bar: 'abc' // violation should be reported here on the unused placeholder property
}
});
},
};
```
> Improve violation reporting location for `no-unused-placeholders`

- lib/rules/no-unused-message-ids.js
- tests/lib/rules/no-unused-message-ids.js
Fixes #283.
When we haven't found any violation reporting code in a rule, we should assume the violation reporting is being handled in an external file/function, so don't flag any violations as they are likely to be false positives.
Changes:
* Adds variable `hasSeenViolationReport` for tracking whether we have seen any violation reporting code
* Renames existing variable to `hasSeenUnknownMessageId ` for clarity
> Fix false positive with `no-unused-message-ids` from external violation reporting function

- lib/rules/require-meta-has-suggestions.js
- tests/lib/rules/require-meta-has-suggestions.js
> Handle spread in `context.report()` in `require-meta-has-suggestions` rule

- lib/rules/require-meta-fixable.js
- tests/lib/rules/require-meta-fixable.js
> Handle spread in `context.report()` in `require-meta-fixable` rule

- lib/rules/no-unused-message-ids.js
- lib/utils.js
- tests/lib/rules/no-missing-message-ids.js
- tests/lib/rules/no-unused-message-ids.js
- tests/lib/utils.js
When a `messageId` from a function parameter is reported, stop trying to detect unused `messageId`s, since we can't currently know what values that function  is called with. In a future improvement, we could try to detect the function calls to find the possible values the parameter is called with.
Fixes #282.
> Fix false positives with violation reporting helper function in `no-unused-message-ids` rule

- lib/rules/meta-property-ordering.js
- lib/rules/no-unused-message-ids.js
- lib/rules/prefer-message-ids.js
- lib/rules/require-meta-docs-description.js
- lib/rules/require-meta-docs-url.js
- lib/rules/require-meta-schema.js
- lib/rules/require-meta-type.js
In most places, we call this variable `ruleInfo` for better clarity. But in some places, we still called it just `info` which is ambiguous. 
This is an internal-only refactoring.
> Rename `info` to `ruleInfo`

- README.md
- docs/rules/consistent-output.md
- docs/rules/fixer-return.md
- docs/rules/meta-property-ordering.md
- docs/rules/no-deprecated-context-methods.md
- docs/rules/no-deprecated-report-api.md
- docs/rules/no-identical-tests.md
- docs/rules/no-missing-message-ids.md
- docs/rules/no-missing-placeholders.md
- docs/rules/no-only-tests.md
- docs/rules/no-unused-message-ids.md
- docs/rules/no-unused-placeholders.md
- docs/rules/no-useless-token-range.md
- docs/rules/prefer-message-ids.md
- docs/rules/prefer-object-rule.md
- docs/rules/prefer-output-null.md
- docs/rules/prefer-placeholders.md
- docs/rules/prefer-replace-text.md
- docs/rules/report-message-format.md
- docs/rules/require-meta-docs-description.md
- docs/rules/require-meta-docs-url.md
- docs/rules/require-meta-fixable.md
- docs/rules/require-meta-has-suggestions.md
- docs/rules/require-meta-schema.md
- docs/rules/require-meta-type.md
- docs/rules/test-case-property-ordering.md
- docs/rules/test-case-shorthand-strings.md
- package.json
- Fixed argument forwarding in the lint script in package.json
- The marker comments now make it clear that the content is auto-generated
https://github.com/bmish/eslint-doc-generator/releases/tag/v0.15.0
> docs: update eslint-doc-generator to 0.15

- package.json
as inline configs was widely used in the source code, I just separate the `eslint --no-inline-config docs` to npm script `lint:docs`.
fixes #140
> chore: use eslint --no-inline-config to eliminate linting warnings in the docs

- .eslint-doc-generatorrc.js
- README.md
- docs/rules/consistent-output.md
- docs/rules/fixer-return.md
- docs/rules/no-deprecated-context-methods.md
- docs/rules/no-deprecated-report-api.md
- docs/rules/no-identical-tests.md
- docs/rules/no-missing-message-ids.md
- docs/rules/no-missing-placeholders.md
- docs/rules/no-only-tests.md
- docs/rules/no-unused-message-ids.md
- docs/rules/no-unused-placeholders.md
- docs/rules/no-useless-token-range.md
- docs/rules/prefer-message-ids.md
- docs/rules/prefer-object-rule.md
- docs/rules/prefer-output-null.md
- docs/rules/require-meta-fixable.md
- docs/rules/require-meta-has-suggestions.md
- docs/rules/require-meta-schema.md
- docs/rules/require-meta-type.md
- package.json
* Move the options to a config file `.eslint-doc-generatorrc.js`
* Add the URL to the configs documentation to link to whenever mentioning configs
Latest release of [eslint-doc-generator](https://github.com/bmish/eslint-doc-generator): https://github.com/bmish/eslint-doc-generator/releases/tag/v0.28.0
> docs: update eslint-doc-generator to 0.28

- .gitignore
- eslint-remote-tester.config.js
- package.json
This runs all our rules on top ESLint plugin repos to ensure that they don't crash. It's like smoke testing. 
https://github.com/AriPerkkio/eslint-remote-tester
> chore: add `eslint-remote-tester`

- lib/rules/no-identical-tests.js
Spent some time this evening profiling eslint on the eslint repo. Noticed that this rule seems to take a little longer than I would've guessed and spend a bit of time with @jviide improving the equality algorithm used for this rule. The result is that the changes in this PR make the rule ~10x faster.
| Before | After |
|--:|--:|
| 453ms | **46ms** |
> perf: use improved comparison algorithm in `no-identical-tests` rule

- .eslint-doc-generatorrc.js
- README.md
- package.json
Split the rules list into two lists, one for rule-implementation-file rules and one for test-file rules. This is a big win for organization that helps make it easier to find and understand the focus of each fule. It also matches how we have separate `rules` / `tests` configs available.
I originally added [eslint-doc-generator](https://github.com/bmish/eslint-doc-generator) in #312. It has a [`--rule-list-split` option](https://github.com/bmish/eslint-doc-generator#configuration-options) that we can use to conveniently split the rules list based on our existing `meta.docs.category` rule property.
> docs: split rules list into rule/test-related rules

- README.md
- docs/rules/prefer-message-ids.md
- lib/rules/prefer-message-ids.js
> Tweak violation message in `prefer-message-ids` rule

- tests/lib/rules/no-only-tests.js
- tests/lib/rules/prefer-output-null.js
fix the ci failing in main: https://github.com/eslint-community/eslint-plugin-eslint-plugin/actions/runs/5594530270/jobs/10229475712
> fix: use latest ECMAScript version in tests

- docs/rules/require-meta-docs-description.md
- docs/rules/require-meta-docs-url.md
- docs/rules/require-meta-fixable.md
- docs/rules/require-meta-schema.md
- lib/rules/consistent-output.js
- lib/rules/require-meta-docs-description.js
- lib/rules/require-meta-docs-url.js
- lib/rules/require-meta-fixable.js
- lib/rules/require-meta-schema.js
- package.json
Moves information about rule options into rule schemas so rule doc option lists can be autogenerated.
Note that I have only added these auto-generated option lists to rules with simple object-based options. Other types of options (enums/arrays/etc) aren't supported yet.
This feature shipped in:
* https://github.com/bmish/eslint-doc-generator/releases/tag/v1.5.0
* https://github.com/bmish/eslint-doc-generator/pull/480
> docs: auto-generate some rule option lists with eslint-doc-generator

- .nycrc
- lib/rules/fixer-return.js
- lib/rules/meta-property-ordering.js
- lib/rules/no-deprecated-context-methods.js
- lib/rules/no-deprecated-report-api.js
- lib/rules/no-identical-tests.js
- lib/rules/no-missing-message-ids.js
- lib/rules/no-missing-placeholders.js
- lib/rules/no-only-tests.js
- lib/rules/no-unused-message-ids.js
- lib/rules/no-unused-placeholders.js
- lib/rules/no-useless-token-range.js
- lib/rules/prefer-message-ids.js
- lib/rules/prefer-object-rule.js
- lib/rules/prefer-output-null.js
- lib/rules/prefer-placeholders.js
- lib/rules/prefer-replace-text.js
- lib/rules/report-message-format.js
- lib/rules/require-meta-docs-description.js
- lib/rules/require-meta-docs-url.js
- lib/rules/require-meta-fixable.js
- lib/rules/require-meta-has-suggestions.js
- lib/rules/require-meta-schema.js
- lib/rules/require-meta-type.js
- lib/rules/test-case-property-ordering.js
- lib/rules/test-case-shorthand-strings.js
- lib/utils.js
- package.json
- tests/lib/utils.js
refs: https://eslint.org/blog/2023/09/preparing-custom-rules-eslint-v9/
> feat: preparing for eslint v9

- .eslint-doc-generatorrc.js
- README.md
- docs/rules/consistent-output.md
- docs/rules/meta-property-ordering.md
- docs/rules/no-deprecated-context-methods.md
- docs/rules/no-deprecated-report-api.md
- docs/rules/no-missing-message-ids.md
- docs/rules/no-missing-placeholders.md
- docs/rules/no-unused-message-ids.md
- docs/rules/no-unused-placeholders.md
- docs/rules/no-useless-token-range.md
- docs/rules/prefer-message-ids.md
- docs/rules/prefer-object-rule.md
- docs/rules/prefer-placeholders.md
- docs/rules/prefer-replace-text.md
- docs/rules/report-message-format.md
- docs/rules/require-meta-docs-description.md
- docs/rules/require-meta-docs-url.md
- docs/rules/require-meta-fixable.md
- docs/rules/require-meta-has-suggestions.md
- docs/rules/require-meta-schema.md
- docs/rules/require-meta-type.md
- docs/rules/test-case-property-ordering.md
- docs/rules/test-case-shorthand-strings.md
> chore: postprocess with prettier in eslint-doc-generator

- lib/utils.js
- tests/lib/utils.js
This adds support for named exports in ESM (whether it be TS or not).
For example:
```ts
export const rule: RuleModule = {
create: () => { ... };
};
```
Also, exported symbols:
```ts
const rule = { ... };
export {rule};
```
While ESLint plugins are still usually CJS at time of writing this, many are written as ESM sources, and an increasing number are using named exports.
You'll want to hide whitespace changes when reviewing this, as prettier reformatted a bunch of it thanks to changing the level of nesting/chaining.
Fixes #375
> feat: support named exports in ESM/TS

- README.md
- docs/rules/no-only-tests.md
- docs/rules/no-property-in-node.md
- docs/rules/require-meta-schema.md
- eslint-remote-tester.config.js
- lib/utils.js
- package.json
- tests/lib/utils.js
fixes #450
To make the ci happy:
* updated eslint-remote-tester config
* upgraded eslint-doc-generator
> fix: false positives in 5.4.0 for functions that aren't ESLint rules

- lib/rules/test-case-property-ordering.js
- tests/lib/rules/meta-property-ordering.js
- tests/lib/rules/no-identical-tests.js
- tests/lib/rules/no-missing-message-ids.js
- tests/lib/rules/no-unused-message-ids.js
- tests/lib/rules/prefer-message-ids.js
- tests/lib/rules/prefer-object-rule.js
- tests/lib/rules/require-meta-docs-description.js
- tests/lib/rules/require-meta-docs-url.js
- tests/lib/rules/require-meta-fixable.js
- tests/lib/rules/require-meta-has-suggestions.js
- tests/lib/rules/require-meta-schema.js
- tests/lib/rules/require-meta-type.js
- tests/lib/rules/test-case-property-ordering.js
> feat!: change test-case-property-ordering to add supports languageOptions

- lib/rules/no-property-in-node.js
- tests/lib/rules/no-property-in-node.js
Adds a new `additionalNodeTypeFiles` option as an array of regular expressions. User configs can specify additional files such as a path to a `node_modules/ ... .d.ts` file.
Fixes #482.
> feat: [no-property-in-node] add additionalNodeTypeFiles option

- README.md
- docs/rules/require-meta-schema-description.md
- lib/rules/consistent-output.js
- lib/rules/meta-property-ordering.js
- lib/rules/report-message-format.js
- lib/rules/require-meta-docs-description.js
- lib/rules/require-meta-schema-description.js
- lib/rules/require-meta-schema.js
- lib/rules/test-case-property-ordering.js
- lib/rules/test-case-shorthand-strings.js
- lib/utils.js
- tests/lib/rules/require-meta-schema-description.js
Fixes #334.
This is a relatively straightforward approach that descends through the AST of `meta.schema`. It doesn't attempt to dynamically construct the properties through AJV. 
I tried it out on typescript-eslint here: https://github.com/typescript-eslint/typescript-eslint/pull/10171
> feat: add `require-meta-schema-description` rule

- README.md
- docs/rules/require-meta-docs-recommended.md
- lib/rules/require-meta-docs-recommended.js
- tests/lib/rules/require-meta-docs-recommended.js
> Add suggestions to `require-meta-docs-recommended` rule

- README.md
- docs/rules/require-meta-default-options.md
- lib/rules/consistent-output.js
- lib/rules/meta-property-ordering.js
- lib/rules/no-property-in-node.js
- lib/rules/report-message-format.js
- lib/rules/require-meta-default-options.js
- lib/rules/require-meta-docs-description.js
- lib/rules/require-meta-docs-recommended.js
- lib/rules/require-meta-docs-url.js
- lib/rules/require-meta-fixable.js
- lib/rules/require-meta-schema.js
- lib/rules/test-case-property-ordering.js
- lib/rules/test-case-shorthand-strings.js
- tests/lib/rules/require-meta-default-options.js
> Add new `require-meta-default-options` rule

- README.md
- docs/rules/no-meta-schema-default.md
- eslint.config.js
- lib/rules/no-meta-schema-default.js
- tests/lib/rules/no-meta-schema-default.js
> Add new `no-meta-schema-default` rule

- README.md
The recommended configuration doesn't set `sourceType` to `script` anymore.
Fixes https://github.com/eslint-community/eslint-plugin-eslint-plugin/issues/514
> Remove mention of `sourceType` in the recommended config

- .github/workflows/main.yml
This change adds node v24 to the matrix for ci testing
Closes #521
> ci: add node v24 to test matrix

- package.json
- tests/lib/rules/no-property-in-node.js
Not external facing.
Includes a fix for:
- https://typescript-eslint.io/blog/announcing-typescript-eslint-v8/#project-service
> chore: update typescript deps

- eslint.config.js
This change updates the eslint config to use `sourceType: 'module'`, and swaps n's `flat/mixed-esm-and-cjs` config for `flat/recommended` which will use the module type from the nearest `package.json`.
> build: fix eslint.config following esm update

- .eslint-doc-generatorrc.ts
Follow-up to:
- https://github.com/eslint-community/eslint-plugin-eslint-plugin/pull/534
https://github.com/bmish/eslint-doc-generator?tab=readme-ov-file#configuration-file
> chore: switch to TypeScript for `.eslint-doc-generatorrc.ts`

- CHANGELOG.md
release-please messed some of this up in https://github.com/eslint-community/eslint-plugin-eslint-plugin/pull/526 so I'm fixing:
- Reorder some items under v7 for consistency
- Move v7 to top of changelog
I also updated the release notes here:
- https://github.com/eslint-community/eslint-plugin-eslint-plugin/releases/tag/v7.0.0
> docs: fix changelog ordering
