eslint-community/eslint-plugin-eslint-plugin

README.md
docs/rules/test-case-property-ordering.md
lib/rules/test-case-property-ordering.js
tests/lib/rules/no-identical-tests.js
tests/lib/rules/test-case-property-ordering.js

New: test-case-property-ordering

---

README.md
docs/rules/no-unused-placeholders.md
lib/rules/no-unused-placeholders.js
tests/lib/rules/no-unused-placeholders.js

New: rule no-unused-placeholders.

---

lib/rules/no-useless-token-range.js

the master build failing due to a linting issue. the pr fixed it.

Chore: fix linting errors

---

package.json

it resolved 2 vulnerabilities:
* mocha > debug: https://nodesecurity.io/advisories/534
* mocha > growl: https://nodesecurity.io/advisories/146

Upgrade: dev dependcies to latest

---

lib/index.js

This reverts commit bb71efaec765691c1cb85bd6d8d6b46a5ae0c960.

Revert "Update: add plugins: ['eslint-plugin'] in configs"

---

tests/lib/rules/require-meta-docs-url.js

ObjectRestSpread has been in es spec.

Chore: fix incorrect test cases.

---

docs/rules/meta-property-ordering.md

Let me know if there are any issues. 😄

Docs: Fix incorrect rule reference in meta-property-ordering

---

.github/workflows/main.yml
.travis.yml

Switch to github actions

---

.github/workflows/main.yml

Run tests under Node 16

---

lib/rules/no-identical-tests.js
package.json
tests/lib/rules/no-identical-tests.js

Improve test coverage of `no-identical-tests` rule

---

lib/rules/no-only-tests.js

https://eslint-utils.mysticatea.dev/api/token-utils.html#iscommatoken-isnotcommatoken

Fix: Use token utilities from `eslint-utils`

---

CHANGELOG.md

Checked for spelling mistakes with https://www.npmjs.com/package/cspell

Docs: Fix typo

---

.eslintrc.js
package.json

refs: https://github.com/not-an-aardvark/eslint-plugin-eslint-plugin/pull/95#issuecomment-888410721

Fix: support eslint v6

---

.github/workflows/main.yml

Follow-up to https://github.com/not-an-aardvark/eslint-plugin-eslint-plugin/pull/172

Test: Add CI test for ESLint 6 compatibility

---

README.md
docs/rules/require-meta-schema.md
lib/rules/require-meta-schema.js
tests/lib/rules/require-meta-schema.js

Fix: Change autofix to suggestion in `require-meta-schema` rule

---

.gitignore
package.json

Quick PR to speed up ESLint with caching.

Add caching to ESLint

---

.eslintrc.js
lib/index.js
lib/rules/require-meta-docs-url.js
lib/utils.js
package.json

Add [eslint-plugin-eslint-comments](https://github.com/mysticatea/eslint-plugin-eslint-comments) especially to do things like:
* Ensure we don't have unused disable comments
* Ensure we have descriptions with our disable comments (current ones grandfathered in)

chore: add `eslint-plugin-eslint-comments`

---

CHANGELOG.md
package.json

I don't have admin access to the repo so I can't push the release commit to main myself. 
```
release-it
...
Push? Yes
ERROR remote: error: GH006: Protected branch update failed for refs/heads/main.        
remote: error: At least 1 approving review is required by reviewers with write access.  
```
Already published to npm: https://www.npmjs.com/package/eslint-plugin-eslint-plugin?activeTab=versions

chore: release v5.0.8

---

docs/rules/prefer-message-ids.md

Add a summary line about the benefits of this rule.

docs: add another justification for prefer-message-ids rule

---

README.md

Fixes https://github.com/eslint-community/eslint-plugin-eslint-plugin/pull/433#discussion_r1479956751.

docs: typo fix in README.md for excluding/including

---

lib/utils.js
tests/lib/utils.js

fixes https://github.com/eslint-community/eslint-plugin-eslint-plugin/issues/455

fix: improve eslint rule detecting

---

lib/index.js

refs: https://github.com/eslint/eslint/pull/18252

feat: add `name` to flat configs

---

README.md
docs/rules/consistent-output.md
lib/rules/consistent-output.js

feat!: remove consistent-output from recommended

---

lib/rules/meta-property-ordering.js

feat!: add `defaultOptions` to meta-property-ordering

---

lib/rules/require-meta-schema-description.js
tests/lib/rules/require-meta-schema-description.js

fix(require-meta-schema-description): handle non-iterable schema properties
